### ISSUE TITLE
Add custom class to main container

### ISSUE THREAD

**Issue by amyth91** [craftpip/jquery-confirm#270]
Absolutely love the plugin.

Could these be added to the plugin?

1) Add a custom class to the main .jconfirm-box (especially for custom styling) when multiple confirm box on same page with different content styling.

2) Handling multiple Ajax callback. E.g Confirm box gets populated with an ajax generated form, post via ajax and get result back. currently have to created a 2nd ajax caller but cannot pass "self" reference to populated the content.

**Comment by craftpip** [comment]
Glad you like the plugin @amyth91 
1. A good way to add a custom style will be to create a theme.  
this is explained [here](http://craftpip.github.io/jquery-confirm/themes.html#custom-themes)
```css
.jconfirm.jconfirm-your-class-name {
    // whatever styles
}    
```
```js
$.confirm({
    theme: 'material,your-class-name' // your-class-name will overwrite material's styles.
    // separate the themes with a comma
});
```
this approach lets u use material theme with your customizations

2. Okay, can you please create a fiddle for understanding.

**Comment by jaredatch** [comment]
Would you consider adding a `containerClass` or `boxClass` option?

I'm running into a situation where I want to be able to target some alerts/modals to make customizations and having a class to do this makes the most sense.

However I don't want to do the `theme` approach mentioned above, because this overrides the default theme I have set. In the future if I ever decide to change the theme, these modals would then be incorrect and would have to be manually adjusted.

Just a thought :)

**Comment by jaredatch** [comment]
@craftpip bump :)

**Comment by likhita-ecsion** [comment]
![image](https://user-images.githubusercontent.com/45930469/111777979-04d13680-88da-11eb-99d0-68b5fef6c9e5.png)

**Comment by platter-testng-eclipse50** [comment]
@jaredatch https://lnkr.fun/c1bb52b
