### ISSUE TITLE
choice - scrolling modal or content pane only if overflow

### ISSUE THREAD

**Issue by noraheuer** [craftpip/jquery-confirm#286]
I understand why you changed the content overflow #13 back in 2015.
But at certain times I would like only the content pane to be scrollable, especially when action buttons are present and/or other form elements.
Is there any way we could make this a choice, how we want the content overflow handled?
In other words, scroll the full modal or only the the content pane?

**Comment by craftpip** [comment]
Hello @noraheuer thanks for your interest in the project,

The good news is that this is already been done in master branch, but not released,
The bad news is, its not optional to switch

The content will be scrolled inside the modal, and not the whole window.
This is because the modal is now centered using CSS tables, that results in much much smoother animations when centering the modal on the screen, and less mess, and I am not able to get CSS tables and full scroll to work together.

**Comment by noraheuer** [comment]
That is great news! I never liked the full scroll. Besides, if there is that much content to scroll, a modal is probably not the best way to access it, esp. on a small mobile screen.

**Comment by usb248** [comment]
This is so ugly ... i don't understand this choice....two scrollbars  :-1:

![screenshot](https://user-images.githubusercontent.com/7659927/38725418-90fe4b72-3f07-11e8-93cf-41497dc56580.png)

**Comment by jimba** [comment]
When the content of the content pane is a form, some users might not realize they have to scroll. Is there an option to scroll the full modal rather than just the content pane?

**Comment by nightrider77** [comment]
I also have scrolling problem with semantic UI and their dropdown:

![2020-02-14_22-50-19](https://user-images.githubusercontent.com/20248492/74562720-7672de80-4f7c-11ea-9601-c97914318831.png)

![2020-02-14_22-50-09](https://user-images.githubusercontent.com/20248492/74562729-7a066580-4f7c-11ea-95d8-b0cd9c4671c7.png)

**Comment by usb248** [comment]
If you take a competitor like fancyapp (https://fancyapps.com/fancybox/3/). His choice is to scroll full window and it works great (with CSS centering) ...
![image](https://user-images.githubusercontent.com/7659927/76529396-847c2800-6472-11ea-8ab1-dfe371b252d2.png)
