### ISSUE TITLE
can i add date picker ?

### ISSUE THREAD

**Issue by Cobra86** [craftpip/jquery-confirm#96]

**Comment by Cobra86** [comment]
![image](https://cloud.githubusercontent.com/assets/7024154/14985034/8e6f885c-113d-11e6-916a-145a51545dde.png)

my issues with jquery ui datepicker

**Comment by dvmobley** [comment]
Do you have a float in there?

Dale

Sent from my iPhone

On May 3, 2016, at 9:45 AM, Cobra86 <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/7024154/14985034/8e6f885c-113d-11e6-916a-145a51545dde.png>

my issues with jquery ui datepicker

**Comment by Cobra86** [comment]
sorry i didn't explain it right but this is what i got when i click to view message, i am not sure why showing the calendar without clicking on the text-box, also because i can't define the date-picker as the html dom not exists so i had to defined after the $.confirm()

![image](https://cloud.githubusercontent.com/assets/7024154/14985785/eab82fbc-1140-11e6-83fe-4d4f561f046a.png)

**Comment by dvmobley** [comment]
It should be in a separate web page. It doesn't have to be a full html page.

Dale

Sent from my iPhone

On May 3, 2016, at 10:09 AM, Cobra86 <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry i didn't explain it right but this is what i got when i click to view message, i am not sure why showing the calendar without clicking on the text-box, also because i can't define the date-picker as the html dom not exists so i had to defined after the $.confirm()

[image]<https://cloud.githubusercontent.com/assets/7024154/14985785/eab82fbc-1140-11e6-83fe-4d4f561f046a.png>
